apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    github.com/project-slug: Sara1996-Darwish/test
spec:
  type: other
  lifecycle: unknown
  owner: backstage-poc
